"use client";
import * as React from "react";import * as DialogPrimitive from "@radix-ui/react-dialog";import {X} from "lucide-react";import {cn} from "@/lib/utils";
const Sheet=DialogPrimitive.Root,SheetTrigger=DialogPrimitive.Trigger,SheetClose=DialogPrimitive.Close,SheetPortal=DialogPrimitive.Portal;
const SheetOverlay=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Overlay>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>>(({className,...props},ref)=><DialogPrimitive.Overlay ref={ref} className={cn("fixed inset-0 z-50 bg-ink/70 backdrop-blur-sm data-[state=open]:animate-fade-in",className)} {...props}/>);SheetOverlay.displayName=DialogPrimitive.Overlay.displayName;
const SheetContent=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>>(({className,children,...props},ref)=><SheetPortal><SheetOverlay/><DialogPrimitive.Content ref={ref} className={cn("fixed inset-y-0 right-0 z-50 grid h-dvh w-[88%] grid-rows-[auto_minmax(0,1fr)] border-l border-border-strong bg-surface-2 sm:max-w-md",className)} {...props}>{children}<DialogPrimitive.Close className="absolute right-4 top-4 flex h-8 w-8 items-center justify-center border border-border text-muted-foreground transition-colors hover:border-border-strong hover:text-text"><X className="h-4 w-4"/><span className="sr-only">Close details</span></DialogPrimitive.Close></DialogPrimitive.Content></SheetPortal>);SheetContent.displayName=DialogPrimitive.Content.displayName;
function SheetHeader({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("shrink-0 border-b border-border px-6 pb-4 pt-6 pr-14",className)} {...props}/>}
const SheetTitle=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Title>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>>(({className,...props},ref)=><DialogPrimitive.Title ref={ref} className={cn("font-display text-xl font-semibold text-text",className)} {...props}/>);SheetTitle.displayName=DialogPrimitive.Title.displayName;
const SheetDescription=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Description>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>>(({className,...props},ref)=><DialogPrimitive.Description ref={ref} className={cn("mt-1.5 text-sm leading-6 text-text-dim",className)} {...props}/>);SheetDescription.displayName=DialogPrimitive.Description.displayName;
export {Sheet,SheetTrigger,SheetClose,SheetContent,SheetHeader,SheetTitle,SheetDescription};
